OBJECT_COLUMNS = [
    "frame_idx",
    "cls",
    "track_id",
    "source",
    "conf",
    "x1",
    "y1",
    "x2",
    "y2",
    "pose_keypoints",
    "label",
]

COCO_OBJECT_CLASSES = [
    "person",
    "bicycle",
    "car",
    "motorcycle",
    "airplane",
    "bus",
    "train",
    "truck",
    "boat",
    "traffic light",
    "fire hydrant",
    "stop sign",
    "parking meter",
    "bench",
    "bird",
    "cat",
    "dog",
    "horse",
    "sheep",
    "cow",
    "elephant",
    "bear",
    "zebra",
    "giraffe",
    "backpack",
    "umbrella",
    "handbag",
    "tie",
    "suitcase",
    "frisbee",
    "skis",
    "snowboard",
    "sports ball",
    "kite",
    "baseball bat",
    "baseball glove",
    "skateboard",
    "surfboard",
    "tennis racket",
    "bottle",
    "wine glass",
    "cup",
    "fork",
    "knife",
    "spoon",
    "bowl",
    "banana",
    "apple",
    "sandwich",
    "orange",
    "broccoli",
    "carrot",
    "hot dog",
    "pizza",
    "donut",
    "cake",
    "chair",
    "couch",
    "potted plant",
    "bed",
    "dining table",
    "toilet",
    "tv",
    "laptop",
    "mouse",
    "remote",
    "keyboard",
    "cell phone",
    "microwave",
    "oven",
    "toaster",
    "sink",
    "refrigerator",
    "book",
    "clock",
    "vase",
    "scissors",
    "teddy bear",
    "hair drier",
    "toothbrush",
]

GAZE_COLUMNS = [
    "frame_idx",
    "track_id",
    "face_detected",
    "face_conf",
    "face_x1",
    "face_y1",
    "face_x2",
    "face_y2",
    "raw_gaze_detected",
    "raw_inout",
    "raw_x_gaze",
    "raw_y_gaze",
    "gaze_detected",
    "inout",
    "x_gaze",
    "y_gaze",
    "offscreen_direction",
    "offscreen_yaw",
    "offscreen_pitch",
]

ANNOTATION_COLUMNS = ["tier", "start_time", "end_time", "gaze"]

IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff", ".webp"}
VIDEO_EXTENSIONS = {".mp4", ".mov", ".avi", ".mkv", ".m4v", ".wmv", ".webm"}
VISUALIZATION_MODES = {"point", "heatmap", "both"}
GAZE_POINT_METHODS = {"argmax", "center_of_mass", "peak_centroid", "peak_region_centroid", "soft_argmax"}
